name: Test & Release!
on:
  push:
    branches:
      - 'master'
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v1
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: install dependencies
        run: |
          # yarn install --no-lockfile
          NO_YARN_POSTINSTALL=1 yarn install --frozen-lockfile
      - name: type check
        run: yarn run type-check-ci
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v1
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: install dependencies
        run: |
          # yarn install --no-lockfile
          NO_YARN_POSTINSTALL=1 yarn install --frozen-lockfile
      - name: lint
        run: yarn run lint
  # https://github.com/semantic-release/npm/blob/1f3ab84a5d05947960be9a7c78642e13fb516496/lib/set-npmrc-auth.js
  release:
    name: Release
    needs:
      - typecheck
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: install dependencies
        run: |
          # yarn install --no-lockfile
          yarn install --frozen-lockfile
      - name: Release (semantic release)
        run: yarn --silent run semantic-release || true
        env: # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
